// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickSchedulerApp.Data;

#nullable disable

namespace QuickSchedulerApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickSchedulerApp.Models.AppointmentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppointmentEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 9, 15, 22, 11, 9, 613, DateTimeKind.Local).AddTicks(8011),
                            Description = " Meeting regarding promotion",
                            Location = "At V local Cafe",
                            Title = "Meeting with Boss"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 9, 15, 22, 11, 9, 613, DateTimeKind.Local).AddTicks(8113),
                            Description = "Meeting with my daughters teachers",
                            Location = "Bagley Elementary School",
                            Title = "Parent Teacher Conference"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 9, 15, 22, 11, 9, 613, DateTimeKind.Local).AddTicks(8115),
                            Description = "Surprise birthday for Grandma",
                            Location = "My house",
                            Title = "Surprise Birthday"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
